### PR TITLE
match only exactly ++ and --

### PR DESCRIPTION
**Pull request by zdhickman**
Current regex matches `++`, `--`, `+-`, and `-+`. After, because of the if/else from L60-63, `+-` and `-+` will subtract from the user. This regex will match specifically `++` and `--`.

screen shot 2015-09-07 at 6 44 23 pm

### CODE REVIEW

**Comment by zdhickman** [comment]
Closing - opening new PR in correct place (https://github.com/hubot-scripts/hubot-plusplus/pull/8)

**Comment by zdhickman** [comment]
Reopening since the [readme](https://github.com/ajacksified/hubot-plusplus/blob/master/README.md) seems to be inaccurate on which repo to open the PR (see https://github.com/ajacksified/hubot-plusplus/pull/47)

**Comment by knuevena** [comment]
+1

**Comment by tevin-otieno** [comment]
+1

**Comment by natdempk** [comment]
:+1:

**Comment by therealklanni** [comment]
Ping @ajacksified

Feel free to add me as a contributor, I don't mind managing PRs.

**Comment by therealklanni** [comment]
Until maintainer comes back from lunch :hamburger:, I am merging these contributions to [therealklanni/hubot-plusplusplus](/therealklanni/hubot-plusplusplus)

**Comment by therealklanni** [comment]
Published v1.2.0 :shipit:

**Comment by zdhickman** [comment]
:bow:

**Pull request merged**
