### PR TITLE
Fixed grammar when reasonScore is 0. Resolves #50.

### LINKED ISSUE #50: Empty-string point count introduces bad grammar
hipchat

### PR DESCRIPTION
**Pull request by danslimmon**

### CODE REVIEW

**Comment by therealklanni** [comment]
:+1:

**Comment by therealklanni** [comment]
Until maintainer comes back from lunch :hamburger:, I am merging these contributions to [therealklanni/hubot-plusplusplus](/therealklanni/hubot-plusplusplus)

**Comment by ajacksified** [comment]
@therealklanni done! I can add you to the npm repo if you give me your info as well.

**Comment by therealklanni** [comment]
@ajacksified what info do you need? My npm username is therealklanni

**Comment by ajacksified** [comment]
@therealklanni that was all I needed to confirm - added to npm!

**Comment by therealklanni** [comment]
Cool. Thanks! I'm going to merge one more and do a publish. Also thinking of getting Travis set up.

**Comment by therealklanni** [comment]
Published v1.2.0

**Pull request merged**
