### PR TITLE
Get hubot off the dried grapes

### PR DESCRIPTION
**Pull request by swalberg**
Perhaps Hubot meant to dispense some raisins, or maybe his French _raisons_ is a bit off, but I'll offer to correct this spelling error.

### CODE REVIEW

**Comment by therealklanni** [comment]
Thanks for contributing! This has come up once before and I believe we declined to make the change because it's not a typo, and is intentional. "raisins" is a play on words. You're "raising" a person's score for this "reason"... Hence "raisins"... Raising reasons.

That being said, I didn't write (that part of) this script and I have no attachment to it. Seems enough people want it changed, so I'll go ahead and merge your PR.

One small request before I merge: can you rewrite your commit message to something more conventional that more clearly describes the change? e.g. "change raisins to reasons" in the imperative as in the example.

Much appreciated, thanks! :metal:

**Comment by swalberg** [comment]
Thanks for reviewing the PR and explaining the history. I've updated the commit message.

**Comment by ajacksified** [comment]
It would be preferable to make it a configuration option rather than changing it outright.

**Comment by swalberg** [comment]
Hi, thanks for the suggestion. I guess I _could_ override that word. It's just that options increase complexity (albeit not a whole lot here) and the reference seems really stretched (given I'm the third person to submit a PR to change it).

If it were to be an option, would you see it as a free form one or a toggle between `reasons` and `raisins`?

**Comment by ajacksified** [comment]
Definitely freeform, with a default of raisins.

**Comment by swalberg** [comment]
Hi Jack, I've added it as a second commit.

**Comment by therealklanni** [comment]
👍 from me

**Comment by ajacksified** [comment]
👍

**Comment by ajacksified** [comment]
published@`v1.2.5`

**Comment by swalberg** [comment]
Thanks!

**Pull request merged**
